function login() {
var username = document.getElementById("username");
if (username.value == "") {
alert("請輸入關卡編號");
}else if(username.value == "a01"){window.location.href="a01.html";} 
else if(username.value == "a02"){window.location.href="a02.html";} 
else if(username.value == "a03"){window.location.href="a03.html";} 
else if(username.value == "a04"){window.location.href="a04.html";} 
else if(username.value == "a05"){window.location.href="a05.html";} 
else if(username.value == "a06"){window.location.href="a06.html";} 
else if(username.value == "a07"){window.location.href="a07.html";} 
else if(username.value == "a08"){window.location.href="a08.html";} 
else if(username.value == "a09"){window.location.href="a09.html";} 
else if(username.value == "a10"){window.location.href="a10.html";} 
else if(username.value == "a11"){window.location.href="a11.html";} 
else if(username.value == "a12"){window.location.href="a12.html";} 
else if(username.value == "b01"){window.location.href="b01.html";} 
else if(username.value == "b02"){window.location.href="b02.html";} 
else if(username.value == "b03"){window.location.href="b03.html";} 
else if(username.value == "b04"){window.location.href="b04.html";} 
else if(username.value == "b05"){window.location.href="b05.html";} 
else if(username.value == "b06"){window.location.href="b06.html";} 
else if(username.value == "b07"){window.location.href="b07.html";} 
else if(username.value == "b08"){window.location.href="b08.html";} 
else if(username.value == "b09"){window.location.href="b09.html";} 
else if(username.value == "b10"){window.location.href="b10.html";} 
else if(username.value == "b11"){window.location.href="b11.html";} 
else if(username.value == "b12"){window.location.href="b12.html";} 
else if(username.value == "c01"){window.location.href="c01.html";} 
else if(username.value == "c02"){window.location.href="c02.html";} 
else if(username.value == "c03"){window.location.href="c03.html";} 
else if(username.value == "c04"){window.location.href="c04.html";} 
else if(username.value == "c05"){window.location.href="c05.html";} 
else if(username.value == "c06"){window.location.href="c06.html";} 
else if(username.value == "c07"){window.location.href="c07.html";} 
else if(username.value == "c08"){window.location.href="c08.html";} 
else if(username.value == "c09"){window.location.href="c09.html";} 
else if(username.value == "c10"){window.location.href="c10.html";} 
else if(username.value == "c11"){window.location.href="c11.html";} 
else if(username.value == "c12"){window.location.href="c12.html";} 
else if(username.value == "d01"){window.location.href="d01.html";} 
else if(username.value == "d02"){window.location.href="d02.html";} 
else if(username.value == "d03"){window.location.href="d03.html";} 
else if(username.value == "d04"){window.location.href="d04.html";} 
else if(username.value == "d05"){window.location.href="d05.html";} 
else if(username.value == "d06"){window.location.href="d06.html";} 
else if(username.value == "d07"){window.location.href="d07.html";} 
else if(username.value == "d08"){window.location.href="d08.html";} 
else if(username.value == "d09"){window.location.href="d09.html";} 
else if(username.value == "d10"){window.location.href="d10.html";} 
else if(username.value == "d11"){window.location.href="d11.html";} 
else if(username.value == "d12"){window.location.href="d12.html";} 
else if(username.value == "aa101"){window.location.href="aa101.html";} 
else if(username.value == "aa102"){window.location.href="aa102.html";} 
else if(username.value == "aa103"){window.location.href="aa103.html";} 
else if(username.value == "aa104"){window.location.href="aa104.html";} 
else if(username.value == "aa105"){window.location.href="aa105.html";} 
else if(username.value == "aa201"){window.location.href="aa201.html";} 
else if(username.value == "aa202"){window.location.href="aa202.html";} 
else if(username.value == "aa203"){window.location.href="aa203.html";} 
else if(username.value == "aa204"){window.location.href="aa204.html";} 
else if(username.value == "aa205"){window.location.href="aa205.html";} 
else if(username.value == "bb101"){window.location.href="bb101.html";} 
else if(username.value == "bb102"){window.location.href="bb102.html";} 
else if(username.value == "bb103"){window.location.href="bb103.html";} 
else if(username.value == "bb104"){window.location.href="bb104.html";} 
else if(username.value == "bb105"){window.location.href="bb105.html";} 
else if(username.value == "bb201"){window.location.href="bb201.html";} 
else if(username.value == "bb202"){window.location.href="bb202.html";} 
else if(username.value == "bb203"){window.location.href="bb203.html";} 
else if(username.value == "bb204"){window.location.href="bb204.html";} 
else if(username.value == "bb205"){window.location.href="bb205.html";} 
else if(username.value == "cc101"){window.location.href="cc101.html";} 
else if(username.value == "cc102"){window.location.href="cc102.html";} 
else if(username.value == "cc103"){window.location.href="cc103.html";} 
else if(username.value == "cc104"){window.location.href="cc104.html";} 
else if(username.value == "cc105"){window.location.href="cc105.html";} 
else if(username.value == "cc201"){window.location.href="cc201.html";} 
else if(username.value == "cc202"){window.location.href="cc202.html";} 
else if(username.value == "cc203"){window.location.href="cc203.html";} 
else if(username.value == "cc204"){window.location.href="cc204.html";} 
else if(username.value == "cc205"){window.location.href="cc205.html";} 
else if(username.value == "dd101"){window.location.href="dd101.html";} 
else if(username.value == "dd102"){window.location.href="dd102.html";} 
else if(username.value == "dd103"){window.location.href="dd103.html";} 
else if(username.value == "dd104"){window.location.href="dd104.html";} 
else if(username.value == "dd105"){window.location.href="dd105.html";} 
else if(username.value == "dd201"){window.location.href="dd201.html";} 
else if(username.value == "dd202"){window.location.href="dd202.html";} 
else if(username.value == "dd203"){window.location.href="dd203.html";} 
else if(username.value == "dd204"){window.location.href="dd204.html";} 
else if(username.value == "dd205"){window.location.href="dd205.html";} 

else {
alert("請輸入正確的關卡編號！")
}
}
